# Generated by Django 4.2.7 on 2025-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('class_year', models.CharField(max_length=50)),
                ('face_embedding_id', models.CharField(blank=True, max_length=100, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='student_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
    ]
