# Generated by Django 4.2.7 on 2025-10-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('class_year', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', 'class_year', 'subject_name'],
                'unique_together': {('department', 'class_year', 'subject_name')},
            },
        ),
    ]
