# Generated by Django 4.2.7

from django.db import migrations


def copy_department_to_old(apps, schema_editor):
    """Copy existing department values to department_old before migration"""
    Student = apps.get_model('students', 'Student')
    Subject = apps.get_model('students', 'Subject')
    
    # Copy department string to department_old for all students
    for student in Student.objects.all():
        if hasattr(student, 'department') and student.department:
            student.department_old = str(student.department)
            student.save()
    
    # Copy department string to department_old for all subjects
    for subject in Subject.objects.all():
        if hasattr(subject, 'department') and subject.department:
            subject.department_old = str(subject.department)
            subject.save()


def migrate_to_fk(apps, schema_editor):
    """Create Department objects and link students/subjects to them"""
    Department = apps.get_model('students', 'Department')
    Student = apps.get_model('students', 'Student')
    Subject = apps.get_model('students', 'Subject')
    
    # Dictionary of departments with their properties
    departments_config = {
        'CSE': {'name': 'Computer Science and Engineering', 'degree_type': 'UG', 'duration_years': 4},
        'MCA': {'name': 'Master of Computer Applications', 'degree_type': 'PG', 'duration_years': 2},
        'ECE': {'name': 'Electronics and Communication Engineering', 'degree_type': 'UG', 'duration_years': 4},
        'EEE': {'name': 'Electrical and Electronics Engineering', 'degree_type': 'UG', 'duration_years': 4},
        'ME': {'name': 'Mechanical Engineering', 'degree_type': 'UG', 'duration_years': 4},
        'CE': {'name': 'Civil Engineering', 'degree_type': 'UG', 'duration_years': 4},
        'IT': {'name': 'Information Technology', 'degree_type': 'UG', 'duration_years': 4},
        'MBA': {'name': 'Master of Business Administration', 'degree_type': 'PG', 'duration_years': 2},
        'MTECH': {'name': 'Master of Technology', 'degree_type': 'PG', 'duration_years': 2},
    }
    
    # Collect all unique departments
    student_depts = set(Student.objects.exclude(department_old__isnull=True).exclude(department_old='').values_list('department_old', flat=True))
    subject_depts = set(Subject.objects.exclude(department_old__isnull=True).exclude(department_old='').values_list('department_old', flat=True))
    all_depts = student_depts | subject_depts
    
    # Create Department objects
    dept_mapping = {}
    for dept_code in all_depts:
        config = departments_config.get(dept_code, {
            'name': dept_code,
            'degree_type': 'UG',
            'duration_years': 4
        })
        
        dept_obj, created = Department.objects.get_or_create(
            code=dept_code,
            defaults=config
        )
        dept_mapping[dept_code] = dept_obj
    
    # Link students to departments
    for student in Student.objects.all():
        if student.department_old and student.department_old in dept_mapping:
            student.department = dept_mapping[student.department_old]
            student.save()
    
    # Link subjects to departments
    for subject in Subject.objects.all():
        if subject.department_old and subject.department_old in dept_mapping:
            subject.department = dept_mapping[subject.department_old]
            subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_department_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_department_to_old, migrations.RunPython.noop),
        migrations.RunPython(migrate_to_fk, migrations.RunPython.noop),
    ]
