# Generated by Django 4.2.7 on 2025-10-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_migrate_to_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department_old',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department_old',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.department'),
        ),
    ]
