#!/bin/bash

echo "🎯 Student Registration - Quick Start"
echo "======================================"
echo ""
echo "✅ Django server is running at: http://localhost:8000"
echo ""
echo "📋 How to test the registration:"
echo ""
echo "1️⃣  Open the dashboard in your browser:"
echo "    open /Users/mohitmaurya/dev/vision/frontend/index.html"
echo ""
echo "2️⃣  Click on 'Register Student' card"
echo ""
echo "3️⃣  Fill in student details:"
echo "    - Roll Number: e.g., CS001"
echo "    - Full Name: e.g., John Doe"
echo "    - Department: Select from dropdown"
echo "    - Year: Select from dropdown"
echo ""
echo "4️⃣  Click 'Open Camera' and allow camera access"
echo ""
echo "5️⃣  Click 'Capture Face' to take the photo"
echo ""
echo "6️⃣  Click 'Register Student' to submit"
echo ""
echo "✨ You should see a success message!"
echo ""
echo "📊 View registered students:"
echo "    curl http://localhost:8000/api/students/"
echo ""
echo "🔍 Check Django admin panel:"
echo "    http://localhost:8000/admin"
echo "    (Create superuser first: python manage.py createsuperuser)"
echo ""
echo "⚠️  Note: AI service is optional for now."
echo "    Students will be registered with 'pending' face embeddings."
echo ""
