// Subject mappings for all departments and years

export const SUBJECTS = {
  // Computer Science and Engineering (CSE) - UG
  "CSE-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Communication Skills",
  ],
  "CSE-Second Year": [
    "Engineering Mathematics-II",
    "Data Structures",
    "Digital Logic Design",
    "Computer Organization",
    "Object Oriented Programming",
    "Discrete Mathematics",
    "Database Management Systems",
    "Operating Systems",
  ],
  "CSE-Third Year": [
    "Design and Analysis of Algorithms",
    "Computer Networks",
    "Software Engineering",
    "Theory of Computation",
    "Compiler Design",
    "Web Technologies",
    "Machine Learning",
    "Microprocessors and Microcontrollers",
  ],
  "CSE-Fourth Year": [
    "Artificial Intelligence",
    "Cryptography and Network Security",
    "Cloud Computing",
    "Big Data Analytics",
    "Mobile Application Development",
    "Internet of Things",
    "Blockchain Technology",
    "Project Work",
  ],

  // Information Technology (IT) - UG
  "IT-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Communication Skills",
  ],
  "IT-Second Year": [
    "Engineering Mathematics-II",
    "Data Structures",
    "Digital Electronics",
    "Computer Architecture",
    "Object Oriented Programming with Java",
    "Discrete Mathematics",
    "Database Management Systems",
    "Operating Systems",
  ],
  "IT-Third Year": [
    "Design and Analysis of Algorithms",
    "Computer Networks",
    "Software Engineering",
    "Web Development",
    "Information Security",
    "Data Mining",
    "Mobile Computing",
    "System Administration",
  ],
  "IT-Fourth Year": [
    "Cloud Computing",
    "Big Data Technologies",
    "DevOps",
    "Network Security",
    "Enterprise Application Development",
    "Cyber Security",
    "IT Project Management",
    "Project Work",
  ],

  // Electronics and Communication Engineering (ECE) - UG
  "ECE-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Communication Skills",
  ],
  "ECE-Second Year": [
    "Engineering Mathematics-II",
    "Network Analysis",
    "Electronic Devices and Circuits",
    "Signals and Systems",
    "Digital Electronics",
    "Electromagnetic Theory",
    "Analog Communication",
    "Circuit Theory",
  ],
  "ECE-Third Year": [
    "Digital Signal Processing",
    "Microprocessors and Microcontrollers",
    "Digital Communication",
    "Control Systems",
    "VLSI Design",
    "Antenna and Wave Propagation",
    "Linear Integrated Circuits",
    "Embedded Systems",
  ],
  "ECE-Fourth Year": [
    "Wireless Communication",
    "Optical Communication",
    "Satellite Communication",
    "Mobile Communication",
    "RF and Microwave Engineering",
    "Digital Image Processing",
    "RADAR Engineering",
    "Project Work",
  ],

  // Electrical and Electronics Engineering (EEE) - UG
  "EEE-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Communication Skills",
  ],
  "EEE-Second Year": [
    "Engineering Mathematics-II",
    "Electrical Circuit Analysis",
    "Electrical Machines-I",
    "Electronic Devices and Circuits",
    "Electrical Measurements",
    "Network Theory",
    "Electromagnetic Fields",
    "Digital Electronics",
  ],
  "EEE-Third Year": [
    "Electrical Machines-II",
    "Power Electronics",
    "Control Systems",
    "Power Systems-I",
    "Microprocessors and Microcontrollers",
    "Electrical Drives",
    "Digital Signal Processing",
    "Transmission and Distribution",
  ],
  "EEE-Fourth Year": [
    "Power Systems-II",
    "High Voltage Engineering",
    "Power System Protection",
    "Renewable Energy Systems",
    "Smart Grid Technology",
    "Electric Vehicle Technology",
    "Industrial Automation",
    "Project Work",
  ],

  // Mechanical Engineering (MECH) - UG
  "MECH-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Engineering Mechanics",
    "Environmental Science",
    "Workshop Practice",
  ],
  "MECH-Second Year": [
    "Engineering Mathematics-II",
    "Strength of Materials",
    "Thermodynamics",
    "Fluid Mechanics",
    "Manufacturing Technology",
    "Engineering Materials",
    "Kinematics of Machinery",
    "Material Science",
  ],
  "MECH-Third Year": [
    "Dynamics of Machinery",
    "Heat Transfer",
    "Design of Machine Elements",
    "Metrology and Measurements",
    "Industrial Engineering",
    "Automobile Engineering",
    "Power Plant Engineering",
    "CAD/CAM",
  ],
  "MECH-Fourth Year": [
    "Finite Element Analysis",
    "Refrigeration and Air Conditioning",
    "Operations Research",
    "Robotics and Automation",
    "Computational Fluid Dynamics",
    "Mechatronics",
    "Renewable Energy Sources",
    "Project Work",
  ],

  // Civil Engineering (CIVIL) - UG
  "CIVIL-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Engineering Mechanics",
    "Environmental Science",
    "Surveying",
  ],
  "CIVIL-Second Year": [
    "Engineering Mathematics-II",
    "Strength of Materials",
    "Fluid Mechanics",
    "Building Materials and Construction",
    "Structural Analysis-I",
    "Geotechnical Engineering",
    "Engineering Geology",
    "Concrete Technology",
  ],
  "CIVIL-Third Year": [
    "Structural Analysis-II",
    "Design of RC Structures",
    "Design of Steel Structures",
    "Transportation Engineering",
    "Water Resources Engineering",
    "Foundation Engineering",
    "Environmental Engineering",
    "Estimation and Costing",
  ],
  "CIVIL-Fourth Year": [
    "Advanced Structural Design",
    "Earthquake Engineering",
    "Construction Management",
    "Infrastructure Engineering",
    "Urban Planning",
    "Remote Sensing and GIS",
    "Prestressed Concrete",
    "Project Work",
  ],

  // Chemical Engineering (CHEM) - UG
  "CHEM-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Basic Chemical Engineering",
  ],
  "CHEM-Second Year": [
    "Engineering Mathematics-II",
    "Chemical Process Calculations",
    "Fluid Mechanics",
    "Heat Transfer",
    "Mass Transfer-I",
    "Thermodynamics",
    "Chemical Engineering Thermodynamics",
    "Organic Chemistry",
  ],
  "CHEM-Third Year": [
    "Mass Transfer-II",
    "Chemical Reaction Engineering",
    "Process Equipment Design",
    "Chemical Process Control",
    "Industrial Chemistry",
    "Mechanical Operations",
    "Petroleum Refining",
    "Process Modeling and Simulation",
  ],
  "CHEM-Fourth Year": [
    "Process Plant Design",
    "Petrochemical Technology",
    "Polymer Engineering",
    "Environmental Engineering",
    "Chemical Process Safety",
    "Biochemical Engineering",
    "Process Economics",
    "Project Work",
  ],

  // AI and Data Science (AI-DS) - UG
  "AI-DS-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in Python",
    "Environmental Science",
    "Communication Skills",
  ],
  "AI-DS-Second Year": [
    "Engineering Mathematics-II",
    "Data Structures",
    "Database Management Systems",
    "Probability and Statistics",
    "Object Oriented Programming",
    "Discrete Mathematics",
    "Digital Logic Design",
    "Web Technologies",
  ],
  "AI-DS-Third Year": [
    "Machine Learning",
    "Deep Learning",
    "Data Mining and Warehousing",
    "Big Data Analytics",
    "Natural Language Processing",
    "Computer Vision",
    "Statistical Methods",
    "Data Visualization",
  ],
  "AI-DS-Fourth Year": [
    "Advanced Machine Learning",
    "Reinforcement Learning",
    "Neural Networks",
    "AI Ethics and Governance",
    "Cloud Computing for Data Science",
    "Time Series Analysis",
    "AI for Business Intelligence",
    "Project Work",
  ],

  // AI and Machine Learning (AI-ML) - UG
  "AI-ML-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in Python",
    "Environmental Science",
    "Communication Skills",
  ],
  "AI-ML-Second Year": [
    "Engineering Mathematics-II",
    "Data Structures and Algorithms",
    "Database Management Systems",
    "Probability and Statistics",
    "Object Oriented Programming",
    "Discrete Mathematics",
    "Linear Algebra",
    "Computer Organization",
  ],
  "AI-ML-Third Year": [
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "Natural Language Processing",
    "Computer Vision",
    "Pattern Recognition",
    "Optimization Techniques",
    "Software Engineering",
  ],
  "AI-ML-Fourth Year": [
    "Advanced Deep Learning",
    "Reinforcement Learning",
    "Generative AI",
    "Edge AI and IoT",
    "MLOps",
    "AI Model Deployment",
    "Ethical AI",
    "Project Work",
  ],

  // Cyber Security (CYBER) - UG
  "CYBER-First Year": [
    "Engineering Mathematics-I",
    "Engineering Physics",
    "Engineering Chemistry",
    "Basic Electrical Engineering",
    "Engineering Graphics",
    "Programming in C",
    "Environmental Science",
    "Communication Skills",
  ],
  "CYBER-Second Year": [
    "Engineering Mathematics-II",
    "Data Structures",
    "Digital Electronics",
    "Computer Networks",
    "Operating Systems",
    "Database Security",
    "Cryptography Fundamentals",
    "Web Technologies",
  ],
  "CYBER-Third Year": [
    "Network Security",
    "Ethical Hacking",
    "Cryptography and Network Security",
    "Application Security",
    "Cyber Laws and Ethics",
    "Digital Forensics",
    "Malware Analysis",
    "Security Testing",
  ],
  "CYBER-Fourth Year": [
    "Advanced Network Security",
    "Cloud Security",
    "IoT Security",
    "Blockchain Security",
    "Penetration Testing",
    "Incident Response",
    "Security Operations",
    "Project Work",
  ],

  // MCA - PG (2 Years)
  "MCA-First Year": [
    "Advanced Database Management Systems",
    "Computer Networks",
    "Software Engineering",
    "Design and Analysis of Algorithms",
    "Object Oriented Programming with Java",
    "Web Technologies",
    "Data Structures",
    "Operating Systems",
  ],
  "MCA-Second Year": [
    "Machine Learning",
    "Cloud Computing",
    "Mobile Application Development",
    "Cyber Security",
    "Big Data Analytics",
    "Software Testing",
    "DevOps",
    "Dissertation",
  ],

  // M.Tech CSE - PG
  "M.TECH-CSE-First Year": [
    "Advanced Data Structures",
    "Advanced Algorithms",
    "Machine Learning",
    "Advanced Database Systems",
    "Research Methodology",
    "Advanced Computer Networks",
    "Software Engineering Principles",
    "Distributed Systems",
  ],
  "M.TECH-CSE-Second Year": [
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Big Data Analytics",
    "Cloud Computing Architecture",
    "Blockchain Technology",
    "Seminar",
    "Thesis Work",
  ],

  // M.Tech VLSI - PG
  "M.TECH-VLSI-First Year": [
    "Advanced Digital Design",
    "VLSI Technology",
    "Analog IC Design",
    "Digital IC Design",
    "CMOS Circuit Design",
    "VLSI Signal Processing",
    "Research Methodology",
    "CAD for VLSI",
  ],
  "M.TECH-VLSI-Second Year": [
    "System on Chip Design",
    "Low Power VLSI Design",
    "ASIC Design",
    "FPGA Based System Design",
    "Mixed Signal IC Design",
    "VLSI Testing",
    "Seminar",
    "Thesis Work",
  ],

  // M.Tech Power Systems - PG
  "M.TECH-PS-First Year": [
    "Advanced Power Systems",
    "Power System Operation and Control",
    "Power System Protection",
    "High Voltage Engineering",
    "Power Electronics",
    "Research Methodology",
    "Renewable Energy Systems",
    "Smart Grid Technology",
  ],
  "M.TECH-PS-Second Year": [
    "Power Quality",
    "FACTS Devices",
    "Energy Management Systems",
    "Electric Drives",
    "Power System Reliability",
    "Distributed Generation",
    "Seminar",
    "Thesis Work",
  ],

  // Add shorter lists for other PG programs
  "M.TECH-SE-First Year": [
    "Advanced Software Engineering",
    "Software Architecture",
    "Software Testing",
    "Agile Methodologies",
    "DevOps Practices",
    "Cloud Native Applications",
    "Research Methodology",
    "Software Project Management",
  ],
  "M.TECH-SE-Second Year": [
    "Microservices Architecture",
    "Software Quality Assurance",
    "Software Metrics",
    "Mobile Software Engineering",
    "Software Maintenance",
    "AI in Software Engineering",
    "Seminar",
    "Thesis Work",
  ],
};

// Get subjects based on department and year
export const getSubjects = (department, year) => {
  if (!department || !year) return [];
  const key = `${department}-${year}`;
  return SUBJECTS[key] || [];
};

// Get all unique subjects (for backward compatibility)
export const getAllSubjects = () => {
  const allSubjects = new Set();
  Object.values(SUBJECTS).forEach((subjectList) => {
    subjectList.forEach((subject) => allSubjects.add(subject));
  });
  return Array.from(allSubjects).sort();
};
